import { TermSource } from '../../constants/enums.constants';

// code is required here even though the DDL admits null: with every row coded, the unique pair
// (source, code) protects the whole table. An API stricter than the schema is the safe direction.
// source is optional on create — it defaults to 'LOCAL' — and immutable on update, where it is
// ignored in silence so a client resending the GET response does not get a 400 for a field it
// never meant to change.
// metadata is deliberately absent: it is not writable from the API. reviewStatus is the only door
// to its content, arrives flat and is merged over the stored object, preserving autoCreated and
// createdFrom
export interface CreateDiagnosticTermInput {
    source?: TermSource;
    code: string;
    name: string;
    termGroup?: string | null;
    reviewStatus?: string;
    isActive?: boolean;
}

// Input of the implicit resolution service (ESAVI-DIAGTERM-006). source is not a parameter: it is
// always LOCAL. operationCode is the code of the endpoint that triggered the resolution, and it is
// stored in metadata.createdFrom so an autogenerated term can be traced back to what created it
export interface ResolveDiagnosticTermInput {
    code: string;
    name: string;
    operationCode: string;
}
