import { initAuthAssociations } from './auth.associations';
import { initAppSessionAssociations } from './appSession.associations';
import { initCatalogAssociations } from './catalog.associations';
import { initGeographicAssociations } from './geographic.associations';
import { initHealthFacilityAssociations } from './healthFacility.associations';
import { initAppUserGeoLocationAssociations } from './appUserGeoLocation.associations';
import { initPatientAssociations } from './patient.associations';
import { initEsaviCaseAssociations } from './esaviCase.associations';
import { initNotifierAssociations } from './notifier.associations';
import { initClassificationAssociations } from './classification.associations';
import { initNotificationAssociations } from './notification.associations';
import { initSevereNotificationAssociations } from './severeNotification.associations';
import { initNonSevereNotificationAssociations } from './nonSevereNotification.associations';
import { initNotificationEventAssociations } from './notificationEvent.associations';
import { initNotificationMedicationAssociations } from './notificationMedication.associations';
import { initNotificationVaccineAssociations } from './notificationVaccine.associations';
import { initNotificationDiluentAssociations } from './notificationDiluent.associations';
import { initNotificationPregnancyAssociations } from './notificationPregnancy.associations';
import { initNotificationPregnancyComplicationAssociations } from './notificationPregnancyComplication.associations';
import { initInvestigationAssociations } from './investigation.associations';
import { initInvestigationSourceAssociations } from './investigationSource.associations';
import { initInvestigationAutopsyAssociations } from './investigationAutopsy.associations';
import { initInvestigationTeamMemberAssociations } from './investigationTeamMember.associations';
import { initInvestigationMedicalHistoryAssociations } from './investigationMedicalHistory.associations';
import { initInvestigationPregnancyConditionAssociations } from './investigationPregnancyCondition.associations';
import { initInvestigationClinicalEvaluationAssociations } from './investigationClinicalEvaluation.associations';
import { initInvestigationVaccinationContextAssociations } from './investigationVaccinationContext.associations';
import { initInvestigationVaccineAdministeredAssociations } from './investigationVaccineAdministered.associations';
import { initInvestigationColdChainAssociations } from './investigationColdChain.associations';
import { initInvestigationAdministrationErrorAssociations } from './investigationAdministrationError.associations';
import { initInvestigationCommunityAssociations } from './investigationCommunity.associations';
import { initFinalClassificationAssociations } from './finalClassification.associations';
import { initEvaluationInstitutionAssociations } from './evaluationInstitution.associations';
import { initSystemConfigAssociations } from './systemConfig.associations';

export const initAssociations = (): void => {
    initAuthAssociations();
    initAppSessionAssociations();
    initGeographicAssociations();
    initCatalogAssociations();
    initHealthFacilityAssociations();
    initAppUserGeoLocationAssociations();
    initPatientAssociations();
    initEsaviCaseAssociations();
    initNotifierAssociations();
    initClassificationAssociations();
    initNotificationAssociations();
    initSevereNotificationAssociations();
    initNonSevereNotificationAssociations();
    initNotificationEventAssociations();
    initNotificationMedicationAssociations();
    initNotificationVaccineAssociations();
    initNotificationDiluentAssociations();
    initNotificationPregnancyAssociations();
    initNotificationPregnancyComplicationAssociations();
    initInvestigationAssociations();
    initInvestigationSourceAssociations();
    initInvestigationAutopsyAssociations();
    initInvestigationTeamMemberAssociations();
    initInvestigationMedicalHistoryAssociations();
    initInvestigationPregnancyConditionAssociations();
    initInvestigationClinicalEvaluationAssociations();
    initInvestigationVaccinationContextAssociations();
    initInvestigationVaccineAdministeredAssociations();
    initInvestigationColdChainAssociations();
    initInvestigationAdministrationErrorAssociations();
    initInvestigationCommunityAssociations();
    initFinalClassificationAssociations();
    initEvaluationInstitutionAssociations();
    initSystemConfigAssociations();
}