import { body, param, query } from 'express-validator';

export const appRoleIdValidator = [
    param('id').notEmpty().withMessage('Role ID is required')
        .isUUID().withMessage('Role ID must be a valid UUID')
        .trim()
];

export const appRoleListValidator = [
    query('limit').optional().isInt({ min: 1, max: 100 })
        .withMessage('Limit must be an integer between 1 and 100'),
    query('offset').optional().isInt({ min: 0 })
        .withMessage('Offset must be a non-negative integer'),
    query('name').optional().trim()
        .isLength({ min: 2 }).withMessage('Name must be at least 2 characters long')
        .isLength({ max: 200 }).withMessage('Name must be at most 200 characters long'),
    query('code').optional().trim()
        .isLength({ min: 2 }).withMessage('Code must be at least 2 characters long')
        .isLength({ max: 100 }).withMessage('Code must be at most 100 characters long')
];

// isSystemRole, isActive and roleId are rejected instead of ignored: a role created through the API
// is always isSystemRole false, activation is governed by 005A/005B, and the ID comes from the database.
export const createAppRoleValidator = [
    body('code').trim().notEmpty().withMessage('Code is required')
        .isLength({ max: 100 }).withMessage('Code must be at most 100 characters long'),
    body('name').trim().notEmpty().withMessage('Name is required')
        .isLength({ max: 200 }).withMessage('Name must be at most 200 characters long'),
    body('description').trim().notEmpty().withMessage('Description is required'),
    body('level').notEmpty().withMessage('Level is required')
        .isInt({ min: 0 }).withMessage('Level must be a non-negative integer'),
    body('isSystemRole').not().exists()
        .withMessage('Is System Role is not accepted. A role created through the API is never a system role.'),
    body('isActive').not().exists()
        .withMessage('Is Active is not accepted. Role activation is governed by its own operations.'),
    body('roleId').not().exists()
        .withMessage('Role ID is not accepted. It is generated by the database.')
];

export const updateAppRoleValidator = [
    body('code').optional().trim().notEmpty().withMessage('Code cannot be empty')
        .isLength({ max: 100 }).withMessage('Code must be at most 100 characters long'),
    body('name').optional().trim().notEmpty().withMessage('Name cannot be empty')
        .isLength({ max: 200 }).withMessage('Name must be at most 200 characters long'),
    body('description').optional().trim().notEmpty().withMessage('Description cannot be empty'),
    body('level').optional().isInt({ min: 0 }).withMessage('Level must be a non-negative integer'),
    body('isSystemRole').not().exists()
        .withMessage('Is System Role is not accepted. A role created through the API is never a system role.'),
    body('isActive').not().exists()
        .withMessage('Is Active is not accepted. Role activation is governed by its own operations.'),
    body('roleId').not().exists()
        .withMessage('Role ID is not accepted. It is generated by the database.')
];
