import { DataTypes, Model, InferAttributes, InferCreationAttributes, CreationOptional, ForeignKey, NonAttribute } from 'sequelize';
import { sequelize } from '../database/connection';
import { InvestigationClinicalEvaluation } from './investigationClinicalEvaluation.model';
import { HealthFacility } from './healthFacility.model';
import { CatalogItem } from './catalogItem.model';
import { AppDetails } from '../types';

// Each institution that clinically evaluated the investigated patient, with the person who attended
// and how to reach them. Second granddaughter of the investigation block and the first one hanging
// from investigationClinicalEvaluation: its foreign key points at the clinical evaluation and not at
// investigation, so the inherited visibility chain is two hops with the state only in the second one
// - the clinical evaluation has no isActive of its own and the only mark it carries is its deletedAt
export class EvaluationInstitution extends Model<InferAttributes<EvaluationInstitution>, InferCreationAttributes<EvaluationInstitution>> {
    // Its own primary key, generated by the database. Unlike investigationClinicalEvaluation, this
    // row does identify itself: the key is not shared with any parent
    declare evaluationInstitutionId: CreationOptional<string>;

    // The column name lies. It is called investigationId and it does not point at investigation: it
    // points at the primary key of investigationClinicalEvaluation, which happens to be the same
    // UUID because that table shares its key with its own parent. The existence to check is the
    // clinical evaluation's, never the investigation's
    declare investigationId: ForeignKey<InvestigationClinicalEvaluation['investigationId']>;

    // Assigned by TRG_evaluationInstitution_setSortOrder (BEFORE INSERT only) and protected by the
    // partial unique index over (investigationId, sortOrder) WHERE deletedAt IS NULL AND sortOrder IS
    // NOT NULL. This is the only one of the nine tables in the setSortOrderByParent loop whose column
    // is nullable and carries no DEFAULT 0 (esaviapp.sql:1114), so unlike its eight sisters there is
    // no notNull validation to dodge: allowNull true, no defaultValue, the INSERT carries NULL and
    // the trigger reads it as "assign it yourself". That is why this entity needs no CREATE_FIELDS.
    // Nothing but ESAVI-EVALINST-005B ever writes it
    declare sortOrder?: CreationOptional<number | null>;

    declare healthFacilityId?: CreationOptional<string | null>;

    // The free text of the institution, kept exactly as the investigator wrote it and coexisting with
    // healthFacilityId when both travel. Only trim() on write - never toTitleCase, so MINSAL does not
    // become Minsal. There is no column to denormalize the master's name into: the client shows
    // institutionName ?? healthFacility.name
    declare institutionName?: CreationOptional<string | null>;

    // ENCRYPTED COLUMNS: they store the esaviCrypt ciphertext and never the plain text, following
    // what the parent already does with clinicalDetailsPersonName. This is the first collection of
    // the repository with encrypted columns, so both listings decrypt row by row. The validator caps
    // the plain text at 120 characters and not at 250: what has to fit in varchar(250) is the
    // ciphertext, which esaviCrypt makes longer than its input
    declare personName?: CreationOptional<string | null>;
    declare personContact?: CreationOptional<string | null>;

    declare evaluationInstitutionTypeItemId?: CreationOptional<string | null>;

    declare notes?: CreationOptional<string | null>;

    declare isActive?: CreationOptional<boolean>;
    declare readonly createdAt?: CreationOptional<Date>;
    declare readonly updatedAt?: CreationOptional<Date>;
    declare deletedAt?: CreationOptional<Date | null>;

    declare sysDetails?: CreationOptional<object | null>;
    declare appDetails?: CreationOptional<AppDetails[] | null>;

    declare clinicalEvaluation?: NonAttribute<InvestigationClinicalEvaluation>;
    declare healthFacility?: NonAttribute<HealthFacility>;
    declare institutionType?: NonAttribute<CatalogItem>;
}

EvaluationInstitution.init({
    evaluationInstitutionId: {
        type: DataTypes.UUID,
        primaryKey: true,
        allowNull: false,
        defaultValue: sequelize.literal('gen_random_uuid()')
    },
    investigationId: {
        type: DataTypes.UUID,
        allowNull: false,
    },
    // allowNull true and no defaultValue, on purpose: see the comment on the attribute above
    sortOrder: {
        type: DataTypes.SMALLINT,
        allowNull: true,
    },
    healthFacilityId: {
        type: DataTypes.UUID,
        allowNull: true,
    },
    // The lengths are explicit so an overlong text fails in Sequelize and not in Postgres
    institutionName: {
        type: DataTypes.STRING(250),
        allowNull: true,
    },
    personName: {
        type: DataTypes.STRING(250),
        allowNull: true,
    },
    personContact: {
        type: DataTypes.STRING(250),
        allowNull: true,
    },
    evaluationInstitutionTypeItemId: {
        type: DataTypes.UUID,
        allowNull: true,
    },
    notes: {
        type: DataTypes.TEXT,
        allowNull: true,
    },
    isActive: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true
    },
    createdAt: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: sequelize.literal('current_timestamp')
    },
    updatedAt: {
        type: DataTypes.DATE
    },
    deletedAt: {
        type: DataTypes.DATE
    },
    sysDetails: {
        type: DataTypes.JSONB,
        allowNull: false,
        defaultValue: {}
    },
    appDetails: {
        type: DataTypes.JSONB,
        allowNull: false,
        defaultValue: []
    }
}, {
    sequelize,
    tableName: 'evaluationInstitution',
    modelName: 'EvaluationInstitution',
    timestamps: false,
    freezeTableName: true,
});
