import { DataTypes, Model, InferAttributes, InferCreationAttributes, CreationOptional, ForeignKey, NonAttribute } from 'sequelize';
import { sequelize } from '../database/connection';
import { Investigation } from './investigation.model';
import { DiagnosticTerm } from './diagnosticTerm.model';
import { CatalogItem } from './catalogItem.model';
import { AppDetails } from '../types';

// Each final diagnosis the investigated patient leaves the investigation with, resolved against the
// clinical master when the investigator supplies a code and kept as free text when he does not. N
// rows per investigation and all of the same clinical rank: sortOrder is presentation and nothing
// else, and no isPrimary marks any of them. It hangs from investigation and not from
// investigationClinicalEvaluation on purpose - a final diagnosis can be known without the clinical
// evaluation having been run, so the inherited visibility is a single hop and reads the parent's
// own isActive
export class InvestigationDiagnostic extends Model<InferAttributes<InvestigationDiagnostic>, InferCreationAttributes<InvestigationDiagnostic>> {
    // Its own primary key, generated by the database
    declare diagnosticId: CreationOptional<string>;

    // Points at investigation itself, with no UNIQUE on it: one investigation, N diagnoses. Unlike
    // investigationPregnancyCondition, the column name says the truth
    declare investigationId: ForeignKey<Investigation['investigationId']>;

    // Never chosen by the client: it is what the resolution against the clinical master returns
    declare diagnosticTermId?: CreationOptional<string | null>;

    // Derived: the text the investigator wrote, kept only when it differs from the master's name.
    // This table has a single text column, so there is nowhere to denormalize the canonical name or
    // the code - both are read from diagnosticTerm through the include
    declare diagnosticRaw?: CreationOptional<string | null>;

    // DATEONLY and not DATE, like hospitalizationDate and investigationStartDate: it travels as the
    // YYYY-MM-DD string with no hour and no zone. The "not in the future" rule lives in the
    // validator and only there - a CHECK over current_date is not immutable and Postgres rejects it
    declare diagnosticDate?: CreationOptional<string | null>;

    // Presumptive, confirmed or differential. The three items are seeded by esaviapp.sql, and the
    // absence of a value is stored as null: nothing substitutes a default, because "presumptive"
    // and "not stated" are not the same thing
    declare diagnosticTypeItemId?: CreationOptional<string | null>;

    // Assigned by TRG_investigationDiagnostic_setSortOrder (BEFORE INSERT only) and protected by the
    // partial unique index over (investigationId, sortOrder) WHERE deletedAt IS NULL. Declared
    // without defaultValue on purpose: a defaultValue of 0 would make the INSERT send an explicit 0,
    // which is exactly the value the trigger reads as "assign it yourself". The create omits the
    // column instead, and nothing but ESAVI-INVDIAG-005B ever writes it
    declare sortOrder?: CreationOptional<number>;

    declare notes?: CreationOptional<string | null>;

    declare isActive?: CreationOptional<boolean>;
    declare readonly createdAt?: CreationOptional<Date>;
    declare readonly updatedAt?: CreationOptional<Date>;
    declare deletedAt?: CreationOptional<Date | null>;

    declare sysDetails?: CreationOptional<object | null>;
    declare appDetails?: CreationOptional<AppDetails[] | null>;

    declare investigation?: NonAttribute<Investigation>;
    declare diagnosticTerm?: NonAttribute<DiagnosticTerm>;
    declare diagnosticType?: NonAttribute<CatalogItem>;
}

InvestigationDiagnostic.init({
    diagnosticId: {
        type: DataTypes.UUID,
        primaryKey: true,
        allowNull: false,
        defaultValue: sequelize.literal('gen_random_uuid()')
    },
    investigationId: {
        type: DataTypes.UUID,
        allowNull: false,
    },
    diagnosticTermId: {
        type: DataTypes.UUID,
        allowNull: true,
    },
    // The length is explicit so an overlong text fails in Sequelize and not in Postgres
    diagnosticRaw: {
        type: DataTypes.STRING(500),
        allowNull: true,
    },
    diagnosticDate: {
        type: DataTypes.DATEONLY,
        allowNull: true,
    },
    diagnosticTypeItemId: {
        type: DataTypes.UUID,
        allowNull: true,
    },
    sortOrder: {
        type: DataTypes.SMALLINT,
        allowNull: false,
    },
    notes: {
        type: DataTypes.TEXT,
        allowNull: true,
    },
    isActive: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true
    },
    createdAt: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: sequelize.literal('current_timestamp')
    },
    updatedAt: {
        type: DataTypes.DATE
    },
    deletedAt: {
        type: DataTypes.DATE
    },
    sysDetails: {
        type: DataTypes.JSONB,
        allowNull: false,
        defaultValue: {}
    },
    appDetails: {
        type: DataTypes.JSONB,
        allowNull: false,
        defaultValue: []
    }
}, {
    sequelize,
    tableName: 'investigationDiagnostic',
    modelName: 'InvestigationDiagnostic',
    timestamps: false,
    freezeTableName: true,
});
