import { DataTypes, Model, InferAttributes, InferCreationAttributes, CreationOptional, ForeignKey, NonAttribute } from 'sequelize';
import { sequelize } from '../database/connection';
import { InvestigationMedicalHistory } from './investigationMedicalHistory.model';
import { DiagnosticTerm } from './diagnosticTerm.model';
import { AppDetails } from '../types';

// Each condition recorded over the pregnancy the investigation's medical history declared confirmed,
// resolved against the clinical master when the investigator supplies a code and kept as free text
// when he does not. First granddaughter of the investigation block: its foreign key points at
// investigationMedicalHistory and not at investigation, so the inherited visibility chain is two
// hops with the state only in the second one - the medical history has no isActive of its own and
// the only mark it carries is its deletedAt
export class InvestigationPregnancyCondition extends Model<InferAttributes<InvestigationPregnancyCondition>, InferCreationAttributes<InvestigationPregnancyCondition>> {
    // Its own primary key, generated by the database. Unlike investigationMedicalHistory, this row
    // does identify itself: the key is not shared with any parent
    declare pregnancyConditionId: CreationOptional<string>;

    // The column name lies. It is called investigationId and it does not point at investigation: it
    // points at the primary key of investigationMedicalHistory, which happens to be the same UUID
    // because that table shares its key with its own parent. The existence to check is the medical
    // history's, never the investigation's
    declare investigationId: ForeignKey<InvestigationMedicalHistory['investigationId']>;

    // Never chosen by the client: it is what the resolution against the clinical master returns
    declare diagnosticTermId?: CreationOptional<string | null>;

    // Derived: the text the investigator wrote, kept only when it differs from the master's name.
    // This table has a single text column, so there is nowhere to denormalize the canonical name or
    // the code - both are read from diagnosticTerm through the include
    declare conditionRaw?: CreationOptional<string | null>;

    // Assigned by TRG_investigationPregnancyCondition_setSortOrder (BEFORE INSERT only) and protected
    // by the partial unique index over (investigationId, sortOrder) WHERE deletedAt IS NULL. Declared
    // without defaultValue on purpose: a defaultValue of 0 would make the INSERT send an explicit 0,
    // which is exactly the value the trigger reads as "assign it yourself". The create omits the
    // column instead, and nothing but ESAVI-INVPREG-005B ever writes it
    declare sortOrder?: CreationOptional<number>;

    declare notes?: CreationOptional<string | null>;

    declare isActive?: CreationOptional<boolean>;
    declare readonly createdAt?: CreationOptional<Date>;
    declare readonly updatedAt?: CreationOptional<Date>;
    declare deletedAt?: CreationOptional<Date | null>;

    declare sysDetails?: CreationOptional<object | null>;
    declare appDetails?: CreationOptional<AppDetails[] | null>;

    declare medicalHistory?: NonAttribute<InvestigationMedicalHistory>;
    declare diagnosticTerm?: NonAttribute<DiagnosticTerm>;
}

InvestigationPregnancyCondition.init({
    pregnancyConditionId: {
        type: DataTypes.UUID,
        primaryKey: true,
        allowNull: false,
        defaultValue: sequelize.literal('gen_random_uuid()')
    },
    investigationId: {
        type: DataTypes.UUID,
        allowNull: false,
    },
    diagnosticTermId: {
        type: DataTypes.UUID,
        allowNull: true,
    },
    // The length is explicit so an overlong text fails in Sequelize and not in Postgres
    conditionRaw: {
        type: DataTypes.STRING(500),
        allowNull: true,
    },
    sortOrder: {
        type: DataTypes.SMALLINT,
        allowNull: false,
    },
    notes: {
        type: DataTypes.TEXT,
        allowNull: true,
    },
    isActive: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true
    },
    createdAt: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: sequelize.literal('current_timestamp')
    },
    updatedAt: {
        type: DataTypes.DATE
    },
    deletedAt: {
        type: DataTypes.DATE
    },
    sysDetails: {
        type: DataTypes.JSONB,
        allowNull: false,
        defaultValue: {}
    },
    appDetails: {
        type: DataTypes.JSONB,
        allowNull: false,
        defaultValue: []
    }
}, {
    sequelize,
    tableName: 'investigationPregnancyCondition',
    modelName: 'InvestigationPregnancyCondition',
    timestamps: false,
    freezeTableName: true,
});
