import { DataTypes, Model, InferAttributes, InferCreationAttributes, CreationOptional, ForeignKey, NonAttribute } from 'sequelize';
import { sequelize } from '../database/connection';
import { Notification } from './notification.model';
import { DiagnosticTerm } from './diagnosticTerm.model';
import { AppDetails } from '../types';

// Each relevant medical history of the notified patient, resolved against the clinical master when
// the notifier supplies a code and kept as free text when he does not. It is the answer to the
// question notification."hasRelevantMedicalHistory" already asked and had nowhere to store: the flag
// says whether there are antecedents, this table says which ones. Structural twin of
// investigationPregnancyCondition with one hop less - that one is a granddaughter and reads its
// state from a parent that has no isActive, while this one hangs straight off notification, which
// does carry its own state. The two are not the same record and neither feeds the other: this is
// what the notifier declared, investigationMedicalHistory is what the investigator later found
export class NotificationMedicalHistory extends Model<InferAttributes<NotificationMedicalHistory>, InferCreationAttributes<NotificationMedicalHistory>> {
    // Its own primary key, generated by the database
    declare medicalHistoryId: CreationOptional<string>;

    // Points at notification and carries no UNIQUE, so N antecedents hang from one notification.
    // Immutable: an antecedent is never moved between notifications
    declare notificationId: ForeignKey<Notification['notificationId']>;

    // Never chosen by the client: it is what the resolution against the clinical master returns
    declare diagnosticTermId?: CreationOptional<string | null>;

    // Derived: the text the notifier wrote, kept only when it differs from the master's name. This
    // table has a single text column, so there is nowhere to denormalize the canonical name or the
    // code - both are read from diagnosticTerm through the include
    declare historyRaw?: CreationOptional<string | null>;

    // Assigned by TRG_notificationMedicalHistory_setSortOrder (BEFORE INSERT only) and protected by
    // the partial unique index over (notificationId, sortOrder) WHERE deletedAt IS NULL. Declared
    // without defaultValue on purpose: a defaultValue of 0 would make the INSERT send an explicit 0,
    // which is exactly the value the trigger reads as "assign it yourself". The create omits the
    // column instead - through the explicit CREATE_FIELDS list, because omitting the value alone
    // does not stop Sequelize's notNull validation from killing the insert first - and nothing but
    // ESAVI-MEDHIST-005B ever writes it
    declare sortOrder?: CreationOptional<number>;

    declare notes?: CreationOptional<string | null>;

    declare isActive?: CreationOptional<boolean>;
    declare readonly createdAt?: CreationOptional<Date>;
    declare readonly updatedAt?: CreationOptional<Date>;
    declare deletedAt?: CreationOptional<Date | null>;

    declare sysDetails?: CreationOptional<object | null>;
    declare appDetails?: CreationOptional<AppDetails[] | null>;

    declare notification?: NonAttribute<Notification>;
    declare diagnosticTerm?: NonAttribute<DiagnosticTerm>;
}

NotificationMedicalHistory.init({
    medicalHistoryId: {
        type: DataTypes.UUID,
        primaryKey: true,
        allowNull: false,
        defaultValue: sequelize.literal('gen_random_uuid()')
    },
    notificationId: {
        type: DataTypes.UUID,
        allowNull: false,
    },
    diagnosticTermId: {
        type: DataTypes.UUID,
        allowNull: true,
    },
    // The length is explicit so an overlong text fails in Sequelize and not in Postgres
    historyRaw: {
        type: DataTypes.STRING(500),
        allowNull: true,
    },
    sortOrder: {
        type: DataTypes.SMALLINT,
        allowNull: false,
    },
    notes: {
        type: DataTypes.TEXT,
        allowNull: true,
    },
    isActive: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true
    },
    createdAt: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: sequelize.literal('current_timestamp')
    },
    updatedAt: {
        type: DataTypes.DATE
    },
    deletedAt: {
        type: DataTypes.DATE
    },
    sysDetails: {
        type: DataTypes.JSONB,
        allowNull: false,
        defaultValue: {}
    },
    appDetails: {
        type: DataTypes.JSONB,
        allowNull: false,
        defaultValue: []
    }
}, {
    sequelize,
    tableName: 'notificationMedicalHistory',
    modelName: 'NotificationMedicalHistory',
    timestamps: false,
    freezeTableName: true,
});
